apiVersion: apps/v1
kind: Deployment
metadata:
  name: day08-app
  labels:
    app: day08-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day08-app
  template:
    metadata:
      labels:
        app: day08-app
    spec:
      containers:
        - name: app
          image: day06-app:1.1.0
          env:
            - name: GREETING
              value: hello
          ports:
            - containerPort: 8080
